import Head from "next/head";
import Header from "@/components/Header";
import Footer from "@/components/Footer";
import Hero from "@/components/Hero";
import Services from "@/components/Services";
import Works from "@/components/Works";

export default function Home() {
  return (
    <>
      <Head>
        <title>Maxence Vallée | Développeur Front-End React</title>
        {/* <meta name="description" content="Generated by create next app" /> */}
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Services />
      <Works />
      <Footer />
    </>
  );
}
